### ISSUE TITLE
Regular Timesteps

### ISSUE THREAD

**Issue by michaelstrupler** [bgctw/RespChamberProc#7]
The raw timesteps of the PICARRO output look like this, i.e. they are not regular:

```R
DATE TIME FRAC_DAYS_SINCE_JAN1 FRAC_HRS_SINCE_JAN1 JULIAN_DAYS EPOCH_TIME  
<IDat> <char> <num> <num> <num> <num>  
1: 2022-05-31 08:01:59.987 150.2931 3607.033 151.2931 1653976920  
2: 2022-05-31 08:02:01.676 150.2931 3607.034 151.2931 1653976922  
3: 2022-05-31 08:02:03.944 150.2931 3607.034 151.2931 1653976924  
4: 2022-05-31 08:02:04.852 150.2931 3607.035 151.2931 1653976925  
5: 2022-05-31 08:02:06.303 150.2931 3607.035 151.2931 1653976926
```

- The function convertToRegularTimesteps creates regular timesteps of 1 sec:

```R
TIMESTAMP CO2_dry CH4_dry H2Oppt NH3_dry N2O_dry Collar h AirTemp  
1 2022-05-31 08:01:59 448.4094 1.992880 12.10567 0.1006285 0.2947989 0 153 24  
2 2022-05-31 08:02:00 448.4094 1.992814 12.10567 0.1006285 0.2947989 0 153 24  
3 2022-05-31 08:02:01 448.4094 1.992749 12.10567 0.1006285 0.2947990 0 153 24  
4 2022-05-31 08:02:02 448.4094 1.992660 12.10567 0.1006303 0.2938241 0 153 24  
5 2022-05-31 08:02:03 448.4095 1.992572 12.10567 0.1006321 0.2928492 0 153 24
```

&nbsp;

- if timesteps are not regular (i.e. if function `convertToRegularTimesteps` is not applied), the function `subsetContiguous` gives an error.

I have added the /functions subfolder here in Oscar's repository: [RespChamberProc/main/functions](https://github.com/oscarperezpriego/ChamberProc/tree/michael/RespChamberProc/main/functions)

**Comment by bgctw** [comment]
"if timesteps are not regular (i.e. if function convertToRegularTimesteps is not applied), the function subsetContiguous gives an error."

Can you, please provide a minimal working example (MWE) of error in `subsetContiguous` with non-equidistant time steps?

The following MWE works with non-equidistant time steps on current master.

```
fName <- system.file(
  "genData/SMANIE_Chamber1_26032015.zip", package = "RespChamberProc")
ds0 <- readDat(
  unz(fName, filename = unzip(fName, list = TRUE)[1,"Name"] ),tz = "UTC")
ds <- ds0 %>% 
  filter(UQ(sym("TIMESTAMP")) < as.POSIXct("2015-03-26 06:29:12", tz = "UTC"))
ds$Pa <- ds$AirPres * 100  # convert hPa to Pa
ds$CO2_dry <- corrConcDilution(ds, colConc = "CO2_LI840", colVapour = "H2O_LI840")
ds$H2O_dry <- corrConcDilution(ds, colConc = "H2O_LI840", colVapour = "H2O_LI840")
ds$VPD <- calcVPD( ds$SurTemp, ds$Pa, ds$H2O_LI840)
#
diff(ds$TIMESTAMP)
ds <- mutate(ds, TIMESTAMP = TIMESTAMP + pmin(0.04, pmax(-0.04,rnorm(n(),0.0, 0.2))))
#
dsChunked <- subsetContiguous(ds, colTime = "TIMESTAMP", colIndex = "Collar") 

```

**Comment by michaelstrupler** [comment]
Hi Thomas,

Please find attached the MWE and the sample data (zipped) we used.


if we don’t interpolate the timesteps and convert them to a regular interval of 1 sec, we get the following error:

Warning message:
Unknown or uninitialised column: `iChunk`. 
> head(dsChunk)
# A tibble: 0 × 1
# ℹ 1 variable: iChunk <fct>

Thanks and best regards,
Michael


￼
￼

--------------------------------------------
Michael Strupler, Dr. Sc.

***@***.***
https://michaelstrupler.quarto.pub/
---------------------------------------------

**Comment by bgctw** [comment]
Dear Michael,

I debugged the code and data that you sent additionally by email.
The problem is with argument "gapLength = 1" in 

```
dsChunk <- subsetContiguous(ds, colTime = "TIMESTAMP", colIndex = "Collar",
                            gapLength = 1, minNRec = 180, minTime = 180, indexNA = 13)
```

where you tell that differences in timestamps larger than 1 second indicate the start of another contiguous series.
The default of 12 seconds is convenient for a chamber that you move around and place it on different collars and initiate another measurement cycle or automatic chambers that only run (an log) each x minutes.

With non-equidistant time steps, there were many changes below 1 second. so that resulting contiguous series were shorter than 180 records or 180s, so that there was no valid contiguous series.

Please, try with an increased value of `gapLength`, or keep the default of 12 seconds.
Then RespChamberProc should work with the original TimeStamps.

Yours
Thomas

**Comment by michaelstrupler** [comment]
Dear Thomas,

Thanks for clarification regarding the increased value of gapLength.
Ok, I see, so the function to create continuous timestamps becomes obsolete.

Thanks again,
Michael

**Comment by michaelstrupler** [comment]
Hi Thomas,

Thought the gapLength should be adapted to the new setup the issue I see is that PICARRO collect data continuously and there is no time off when moving the chamber except the valve (collar) number. 

Cheers
Oscar

**Comment by bgctw** [comment]
Dear Oscar, note the "either" in the function documentation: "to determine these chunks, either a change in an index variable (input by between the measurements) or a gap in time is used."
